### PR TITLE
Add ffmpeg option and fix small bug with notification framework.

### PR DESCRIPTION
**Pull request by thrdev**
New UI changes:
image

### CODE REVIEW

**Comment by thrdev** [comment]
fixes #67

**Comment by thrdev** [comment]
@Tursko can you test this tomorrow?

**Comment by Tursko** [comment]
Yes. Can you elaborate more on the notification bug?

**Comment by thrdev** [comment]
> Yes. Can you elaborate more on the notification bug?

https://github.com/shotr-io/shotr-3/pull/104/files#diff-2567da71b828d28c58955923768cc02102bd0b517f87797ab840a52fa5baf302R30

Specifically this part.

**Review by Tursko — APPROVED** [review]
Worked as expected. Tested with different qualities. 

Change approved.

**Pull request merged**
